services:
  api:
    build: .
    container_name: event-api
    command: yarn dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    depends_on:
      - db
      - redis

  db:
    image: postgres:15
    container_name: event-db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: events

  redis:
    image: redis:7
    container_name: event-redis
    ports:
      - "6379:6379"

volumes:
  pgdata:
