# fly.toml app configuration file generated for your-event-api on 2024-12-06T18:03:26Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'your-event-api'
primary_region = 'iad'

[build]

[deploy]
  release_command = 'npx prisma migrate deploy'

[env]
  NODE_ENV = 'production'
  PORT = '3000'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [[http_service.checks]]
    interval = '30s'
    timeout = '5s'
    grace_period = '10s'
    method = 'GET'
    path = '/api/health'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
